"""empty message

Revision ID: 3f35beb5bf4a
Revises: 84a81354a358
Create Date: 2021-08-18 15:12:21.608504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func

# revision identifiers, used by Alembic.
revision = '3f35beb5bf4a'
down_revision = '84a81354a358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('accounts', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True,server_default=func.now()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'updated_at')
    op.drop_column('accounts', 'created_at')
    # ### end Alembic commands ###
