"""empty message

Revision ID: 71f2dc0b7722
Revises: 3f35beb5bf4a
Create Date: 2021-09-07 09:59:56.878632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71f2dc0b7722'
down_revision = '3f35beb5bf4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'new_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('new_name', sa.VARCHAR(length=80), server_default=sa.text("'adana'::character varying"), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
