"""empty message

Revision ID: afef02a05181
Revises: 71f2dc0b7722
Create Date: 2021-09-13 15:26:30.108022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afef02a05181'
down_revision = '71f2dc0b7722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
