"""empty message

Revision ID: ba74b9a6b8f7
Revises: 25373189c583
Create Date: 2021-08-16 18:02:16.111231

"""
from alembic import op
import sqlalchemy as sa
import datetime

# revision identifiers, used by Alembic.
revision = 'ba74b9a6b8f7'
down_revision = '02f4cab2ba51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True,server_default=datetime.datetime.utcnow))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=80),
               nullable=True,
               existing_server_default=sa.text("'adana'::character varying"))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=80),
               nullable=False,
               existing_server_default=sa.text("'adana'::character varying"))
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
